package junglesweeper;

import junglesweeper.gameobjects.GameObject;
import junglesweeper.gameobjects.GameObjectsType;

/**
 * Created by codecadet on 27/05/17.
 */
public class Level {

    private GameObjectsType[][] levelMatrix;

    public Level (){

        levelMatrix = new GameObjectsType[][] {{GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH},
                {GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.KEY,GameObjectsType.ROCK,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH},
                {GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.TIGER, GameObjectsType.ROCK, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.ROCK, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.TIGER, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH},
                {GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.TIGER, GameObjectsType.ROCK, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.TIGER, GameObjectsType.BUSH, GameObjectsType.ROCK, GameObjectsType.ROCK, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.TIGER, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH},
                {GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH, GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER},
                {GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.DOOR},
                {GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.ROCK,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.ROCK,GameObjectsType.BUSH,GameObjectsType.TIGER,GameObjectsType.BUSH,GameObjectsType.BUSH,GameObjectsType.BUSH}};
    }

    public GameObjectsType[][] getLevelMatrix() {
        return levelMatrix;
    }
}
